### ISSUE TITLE
Assay Missing

### ISSUE THREAD

**Issue by pietrofranceschi** [ISA-tools/Risa#29]
Dear all,
first of all many thanks for your nice work.
I'm currently working on an ISA tab file for a big Metabolights submission. The file was created with ISA creator with the 2014 Metabolights configuration file. 
The file is composed of 1 investigation, 1 study and  7 different assays of different nature (i.e. I have 9 txt files in my folder). The automatic check of consistency of ISACreator is successful. 
When I load the ISA tab file with Risa, however, I can find only 5 of my 7 assays. What can be the reason of that?
Thank you in advance for your help 

Pietro

R: version 3.1.1 (2014-07-10)
Risa: Version: 1.8.0

**Comment by agbeltran** [comment]
Hi Pietro,

Thanks for your message. Are you getting any error message or the parser seems to work but you are missing two assays?

Thanks

**Comment by pietrofranceschi** [comment]
Hi Alejandra,
the parser works fine, only the assays are missing. To be even more precise (maybe this will help), when I first experienced this problem I have been able to fix it by manually updating some of the infos in the investigation file with Openoffice (the field specifying one of the the instruments  was empty).  After that I've been fixing some filenames in my sample description with ISAcreator ... but now the assays are another time missing and the investigation file seems to be complete  ... and ISACreator is validating my file.
I hope this is not too confusing :-) ...
Thanks for your fast reply!
Pietro

**Comment by agbeltran** [comment]
Would it be possible for you to share the files with me? Then I can test on my side.

**Comment by pietrofranceschi** [comment]
no problem, how can I send them to you?

**Comment by agbeltran** [comment]
Please, email them to: alejandra.gonzalezbeltran@oerc.ox.ac.uk
Thanks!

**Comment by agbeltran** [comment]
Resolved.
